const h = {
    mainPicture: '',
    http: '//img.artstudent.cn/pr/2019-11-12/c9b64314422f4ab582880976b8f109be.jpg,http://img.artstudent.cn/pr/2019-11-12/9097f591003446b1a8529d5c8db721db.jpg,/images/wish/noimages.png',
    srviceTypeIDs: '',
    chinaSrviceTypeIDs: '',
    tagNames: '',
    profIDs: [8, 33, 67, 70, 75, 81],
    enrollRequire: '',
    enrollTargets: 1,
    profCategorys: 1,
    budgets: 1,
    schoolID: 77777,
    insertFlag: 1,
    schoolCode: 77777,
    englishName: 'ceshixueyuan',
    schoolName: '海葵演示环境国外院校',
    hotOrder: 1,
    showOrder: 100,
    groupID: '',
    extOrder: 1,
    extHotFlag: 1,
    logo: '',
    http: '//img.artstudent.cn/pr/2019-11-12/79d600a1e92c4d4fbd8a702b4b429128.png',
    attribute: 1,
    sellingPoint: '环境优美',
    internatRanking: 9,
    profRanking: 9,
    countryID: 56,
    countryName: '意大利',
    labelList: '',
    labelList: '',
    locate: '意大利',
    admissionCall: '',
    onlineConsult: '',
    enrollTarget: 1,
    profCategory: 1,
    budget: 1,
    basicInfo: '基础信息',
    lodgCondit: '',
    hotFlag: 1,
    recommendOrder: 123,
    enrollBase: 0,
    enrollStartTime: '',
    enrollEndTime: '',
    baseSub: '',
    status: 1,
    applicatStatus: 2,
    applicatCondit: '',
    chinaGainPlanUrl: '',
    applicateUrl: '',
    costReference: '',
    chinaExamStatus: 2,
    chinaApplicatCondit: '',
    chinaCostReference: '',
    profLabelType: 1,
    profID: 8,
    profID: 33,
    profID: 67,
    profID: 70,
    profID: 75,
    profID: 81,
    profLabel: '',
}

Object.keys(h).map((key) => {
    // s += `/** \n * title \n * @param {*} ${key}\n */ \n`
    console.log(` * @param {*} ${key}`);
})